/**:
ros__parameters:
alarm_msg: -1
ats: -1
baud_rate: -1
cloud_topic: cloud
custom_error_circle: 3
custom_error_scale: 0.9
dev_id: -1
direction: -1
fitter_filter_window: 1
fitter_isopen: false
fitter_max_range: 7.0
fitter_max_range_difference: 0.1
fitter_min_range: 0.15
fitter_type: 1
frame_id: laser
from_zero: false
group_ip: 224.1.1.91
hard_resample: false
inverted: false
is_group_listener: false
localport: 6668
max_angle: 3.141592653589793
max_dist: 12.0
min_angle: -3.141592653589793
min_dist: 0.1
num: 1
output_360: true
output_cloud: false
output_cloud2: false
output_scan: false
port: /dev/LHLiDAR
range_max: 180.0
range_min: -180.0
raw_bytes: 3
resample: -1.0
reversed: false
rpm: -1
scan_topic: scan
soft_resample: false
time_mode: 0
type: uart
unit_is_mm: -1
use_sim_time: false
uuid: -1
with_angle_filter: false
with_confidence: -1
with_deshadow: -1
with_smooth: -1